### ISSUE TITLE
Niedziałający link do dysku Google

### ISSUE THREAD

**Issue by Goodosky** [wernexnrs/MATURA-INFORMATYKA#18]
https://github.com/wernexnrs/MATURA-INFORMATYKA/blob/94f9c2ef5d1acb66a8d8fb1442a787f0c990d9ff/docs/README.md?plain=1#L110

Podany link do Google Drive nie działa. Wywala 404

**Comment by wernexnrs** [comment]
Usunięty z materiałów. Nie posiadam jego zawartości.
