### ISSUE TITLE
Braki w algorytmie sortowania przez scalanie.

### ISSUE THREAD

**Issue by Tymisko** [wernexnrs/MATURA-INFORMATYKA#8]
W algorytmie sortowania przez scalanie brakuje na koncu funkcji `return tab`, funkcja nie zwraca wyniku.
W dodatku w pseudokodzie nie został zadeklarowany mid, czyli  #srodkowa wartość. Jest ona wykorzystywana ale nie jest zadeklarowana.

**Comment by wernexnrs** [comment]
Algorytm sortuje obiekt w miejscu, funkcja po wykonaniu sortowania nie powinna zwracać niczego w takim wypadku. Pseudokod poprawiony. Dodałem również deklaracje dzielenia całkowitego.
